<?php


namespace Mq\Avatar\Facades;


use Illuminate\Support\Facades\Facade;

class Avatar extends Facade
{
    public static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return "mqAvatar";
    }

}