<?php

namespace Mq\Avatar;


use Illuminate\Support\ServiceProvider;

class AvatarProvider extends ServiceProvider
{
    public function boot(){
        $this->publishes([
            __DIR__."/config/mq.php"=>config_path("mq.php"),
        ]);
    }

    public function register()
    {
//        parent::register(); // TODO: Change the autogenerated stub
        $this->app->singleton("mqAvatar",function($app){
            return new Avatar();
        });
    }
}